<a href="https://colab.research.google.com/github/sumanamishra1120-ux/ybi_foundation/blob/main/Pandas_Read_and_Write_External_Files.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Read and Write External Files

# **Read External File**

In [1]:
# Import pandas libray
import pandas as pd

In [ ]:
# Read CSV file
csv_file = pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Titanic.csv')
csv_file

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.50,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.00,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.00,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [ ]:
# Read Excel file
excel_file = pd.read_excel('https://github.com/YBIFoundation/Dataset/raw/main/Titanic.xlsx')
excel_file

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.50,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.00,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.00,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [ ]:
# Read JSON file
json_file = pd.read_json('https://github.com/YBIFoundation/Dataset/raw/main/Titanic.json')
json_file

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.55,C22 C26,S,11,,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,,,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,,,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,,C,,328,
1305,3,0,"Zabour, Miss. Thamine",female,,1,0,2665,14.4542,,C,,,
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.225,,C,,304,
1307,3,0,"Zakarian, Mr. Ortin",male,27,0,0,2670,7.225,,C,,,
1308,3,0,"Zimmerman, Mr. Leo",male,29,0,0,315082,7.875,,S,,,

# **🦉Practice Problem**

## **Practice Problem 1: Read Chance of Admission CSV File**

In [ ]:
# Read CSV file
admission = pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Admission%20Chance.csv')
admission

,Serial No,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95

## **Practice problem 2: Read Semicolon CSV**

In [ ]:
# Read CSV file
titanic_semicolon = pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Titanic%20Semicolon.csv',delimiter=';')
titanic_semicolon

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,1,0,"Douglas, Mr. Walter Donald",male,50.00,1,0,PC 17761,106.4250,C86,C,NaN,62.0,"Deephaven, MN / Cedar Rapids, IA"
97,1,1,"Douglas, Mrs. Frederick Charles (Mary Helene B...",female,27.00,1,1,PC 17558,247.5208,B58 B60,C,6,NaN,"Montreal, PQ"
98,1,1,"Douglas, Mrs. Walter Donald (Mahala Dutton)",female,48.00,1,0,PC 17761,106.4250,C86,C,2,NaN,"Deephaven, MN / Cedar Rapids, IA"
99,1,1,"Duff Gordon, Lady. (Lucille Christiana Sutherl...",female,48.00,1,0,11755,39.6000,A16,C,1,NaN,London / Paris
100,1,1,"Duff Gordon, Sir. Cosmo Edmund",male,49.00,1,0,PC 17485,56.9292,A20,C,1,NaN,London / Paris

# **🐌Exercise**

## **Exercise 1: Read Bank Churn Data**

Datset Url: https://github.com/YBIFoundation/Dataset/blob/main/Bank%20Churn%20Modelling.csv

In [3]:
# Your answer

import pandas as pd

# Read Bank Churn Data
url = "https://raw.githubusercontent.com/YBIFoundation/Dataset/main/Bank%20Churn%20Modelling.csv"

df = pd.read_csv(url)

# Display the data
print(df)

      CustomerId    Surname  CreditScore Geography  Gender  Age  Tenure  \
0       15634602   Hargrave          619    France  Female   42       2
1       15647311       Hill          608     Spain  Female   41       1
2       15619304       Onio          502    France  Female   42       8
3       15701354       Boni          699    France  Female   39       1
4       15737888   Mitchell          850     Spain  Female   43       2
...          ...        ...          ...       ...     ...  ...     ...
9995    15606229   Obijiaku          771    France    Male   39       5
9996    15569892  Johnstone          516    France    Male   35      10
9997    15584532        Liu          709    France  Female   36       7
9998    15682355  Sabbatini          772   Germany    Male   42       3
9999    15628319     Walker          792    France  Female   28       4

        Balance  Num Of Products  Has Credit Card  Is Active Member  \
0          0.00                1                1                 1
1      83807.86                1                0                 1
2     159660.80                3                1                 0
3          0.00                2                0                 0
4     125510.82                1                1                 1
...         ...              ...              ...               ...
9995       0.00                2                1                 0
9996   57369.61                1                1                 1
9997       0.00                1                0                 1
9998   75075.31                2                1                 0
9999  130142.79                1                1                 0

      Estimated Salary  Churn
0            101348.88      1
1            112542.58      0
2            113931.57      1
3             93826.63      0
4             79084.10      0
...                ...    ...
9995          96270.64      0
9996         101699.77      0
9997          42085.58      1
9998          92888.52      1
9999          38190.78      0

[10000 rows x 13 columns]

## **Exercise 2: Read Population Data**

Dataset Url: https://github.com/YBIFoundation/Dataset/blob/main/Population2030-2040.xlsx

In [4]:
# Your answer
import pandas as pd

url = "https://raw.githubusercontent.com/YBIFoundation/Dataset/main/Population2030-2040.xlsx"

df = pd.read_excel(url)

df

,LocID,Location,Time,AgeGrp,AgeGrpStart,AgeGrpSpan,PopMale,PopFemale,PopTotal
0,4.0,Afghanistan,2030.0,0-4,0.0,5.0,3020.571,2871.955,5892.526
1,8.0,Albania,2030.0,0-4,0.0,5.0,68.824,63.581,132.405
2,12.0,Algeria,2030.0,0-4,0.0,5.0,2116.681,2026.749,4143.430
3,24.0,Angola,2030.0,0-4,0.0,5.0,3714.206,3649.187,7363.393
4,28.0,Antigua and Barbuda,2030.0,0-4,0.0,5.0,3.452,3.354,6.806
...,...,...,...,...,...,...,...,...,...
45971,308.0,Grenada,2040.0,100+,100.0,-1.0,0.001,0.004,0.005
45972,426.0,Lesotho,2040.0,100+,100.0,-1.0,0.001,0.009,0.010
45973,516.0,Namibia,2040.0,100+,100.0,-1.0,0.001,0.003,0.004
45974,690.0,Seychelles,2040.0,100+,100.0,-1.0,0.001,0.007,0.008
45975,776.0,Tonga,2040.0,100+,100.0,-1.0,0.001,0.000,0.001

---